name: Talks-MolSysMT@uibcdf_3.10
channels:
- uibcdf
- conda-forge
- defaults
dependencies:
- python=3.10
- numba
- pip
- numpy
- plotly
- matplotlib
- molsysmt
- openenm
- nglview
- jupyterlab
- rise
- jsonschema-with-format-nongpl
- webcolors

